name       : akonadi
version    : 23.04.3
release    : 87
source     :
    - https://cdn.download.kde.org/stable/release-service/23.04.3/src/akonadi-23.04.3.tar.xz : 2b53d72291c6cfb692f0683a3a089b2294adeb8f9d0794b2c174d15c5a48f74a
license    : LGPL-2.1-or-later
homepage   : https://kde.org
summary    :
    - KDE centralized database to store, index and retrieve the user's personal information
    - mariadb : MariaDB backend for Akonadi
description:
    - The Akonadi framework is responsible for providing applications with a centralized database to store, index and retrieve the user's personal information. This includes the user's emails, contacts, calendars, events, journals, alarms, notes, etc.
    - mariadb : MariaDB backend for Akonadi, opposed to the default SQlite3. Users wanting to run the MariaDB backend require to change Akonadi settings as well as installing this package.
optimize   :
    - lto
component  :
    - desktop.library
    - mariadb : desktop.library
builddeps  :
    - pkgconfig(accounts-qt5)
    - pkgconfig(liblzma)
    - pkgconfig(libxslt)
    - pkgconfig(mariadb)
    - pkgconfig(sqlite3)
    - kaccounts-integration-devel
    - kcrash-devel
    - kiconthemes-devel
    - kio-devel
    - kitemmodels-devel
    - libboost-devel
rundeps    :
    - akonadi-mariadb # It's temporary.
    - devel :
        - kitemmodels-devel
        - libboost-devel
    - mariadb :
        - mariadb-server
setup      : |
    %cmake_ninja \
        -DBUILD_TESTING=OFF \
        -DDATABASE_BACKEND=SQLITE \
        -DINSTALL_APPARMOR=ON
build      : |
    %ninja_build
install    : |
    %ninja_install
    rm $installdir/etc/apparmor.d/{mysql*,postgres*}
patterns   :
    - devel :
        - /usr/bin/akonadi_knut_resource
        - /usr/lib64/qt5/plugins/akonadi/akonadi_test_searchplugin.so
        - /usr/share/akonadi/agents/knutresource.desktop
        - /usr/share/kf5/akonadi_knut_resource/knut-template.xml
        - /usr/share/locale/*/LC_MESSAGES/akonadi_knut_resource.mo
    - mariadb :
        - /etc/apparmor.d/mariadbd*
        - /etc/xdg/akonadi/mysql* # TODO: stateless
