name       : akonadi
version    : 18.04.1
release    : 12
source     :
    - https://cdn.download.kde.org/stable/applications/18.04.1/src/akonadi-18.04.1.tar.xz : 1b1a569df956f7b44fe5b984d54069c176259f977dfd0456b9f33fab12c9e035
license    : LGPL-2.1
component  : desktop.library
optimize   : lto
summary    : The Akonadi framework is responsible for providing applications with a centralized database to store, index and retrieve the user's personal information.
description: |
    The Akonadi framework is responsible for providing applications with a centralized database to store, index and retrieve the user's personal information. This includes the user's emails, contacts, calendars, events, journals, alarms, notes, etc.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(libxslt)
    - pkgconfig(libpq)
    - pkgconfig(mariadb)
    - pkgconfig(Qt5Designer)
    - pkgconfig(sqlite3)
    - extra-cmake-modules
    - kcrash-devel
    - kdbusaddons-devel
    - kdesignerplugin-devel
    - ki18n-devel
    - kiconthemes-devel
    - kio-devel
    - kitemmodels-devel
    - kwindowsystem-devel
    - libboost-devel
    - shared-mime-info
rundeps    :
    - mariadb-server
patterns   :
    - devel :
        - /usr/bin/akonadi_knut_resource
        - /usr/lib64/qt5/plugins/akonadi/akonadi_test_searchplugin.so
        - /usr/share/akonadi/agents/knutresource.desktop
        - /usr/share/kf5/akonadi_knut_resource/knut-template.xml
        - /usr/share/locale/*/LC_MESSAGES/akonadi_knut_resource.mo
setup      : |
    %patch -p1 < $pkgfiles/0001-Fix-mysql-global.conf-paths-after-transition.patch
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
