name       : akonadi
version    : 21.12.1
release    : 73
source     :
    - https://cdn.download.kde.org/stable/release-service/21.12.1/src/akonadi-21.12.1.tar.xz : d43833f1e587aacb758ed42b7431eea908dc6c69cf89183afcd9059d511b08c6
homepage   : https://kde.org/
license    : LGPL-2.1-or-later
component  : desktop.library
summary    : The Akonadi framework is responsible for providing applications with a centralized database to store, index and retrieve the user's personal information
description: |
    The Akonadi framework is responsible for providing applications with a centralized database to store, index and retrieve the user's personal information. This includes the user's emails, contacts, calendars, events, journals, alarms, notes, etc.
builddeps  :
    - pkgconfig(accounts-qt5)
    - pkgconfig(libxslt)
    - pkgconfig(libpq)
    - pkgconfig(mariadb)
    - pkgconfig(signond)
    - pkgconfig(sqlite3)
    - kaccounts-integration-devel
    - kcrash-devel
    - kiconthemes-devel
    - kio-devel
    - kitemmodels-devel
    - libboost-devel
rundeps    :
    - mariadb-server
    - devel :
        - kitemmodels-devel
        - libboost-devel
patterns   :
    - devel :
        - /usr/bin/akonadi_knut_resource
        - /usr/lib64/qt5/plugins/akonadi/akonadi_test_searchplugin.so
        - /usr/share/akonadi/agents/knutresource.desktop
        - /usr/share/kf5/akonadi_knut_resource/knut-template.xml
        - /usr/share/locale/*/LC_MESSAGES/akonadi_knut_resource.mo
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF -DINSTALL_APPARMOR=FALSE
build      : |
    %ninja_build
install    : |
    %ninja_install
