name       : akonadi
version    : 19.04.0
release    : 31
source     :
    - https://cdn.download.kde.org/stable/applications/19.04.0/src/akonadi-19.04.0.tar.xz : c0a2c4259b51293d21487cfe2295df6e8dcfb7ab50eb1a698f531dc7d3253e9a
license    : LGPL-2.1-or-later
component  : desktop.library
summary    : The Akonadi framework is responsible for providing applications with a centralized database to store, index and retrieve the user's personal information
description: |
    The Akonadi framework is responsible for providing applications with a centralized database to store, index and retrieve the user's personal information. This includes the user's emails, contacts, calendars, events, journals, alarms, notes, etc.
builddeps  :
    - pkgconfig(libxslt)
    - pkgconfig(libpq)
    - pkgconfig(mariadb)
    - pkgconfig(Qt5Designer)
    - pkgconfig(sqlite3)
    - extra-cmake-modules
    - kcrash-devel
    - kdbusaddons-devel
    - kdesignerplugin-devel
    - ki18n-devel
    - kiconthemes-devel
    - kio-devel
    - kitemmodels-devel
    - kwindowsystem-devel
    - libboost-devel
    - shared-mime-info
rundeps    :
    - mariadb-server
patterns   :
    - devel :
        - /usr/bin/akonadi_knut_resource
        - /usr/lib64/qt5/plugins/akonadi/akonadi_test_searchplugin.so
        - /usr/share/akonadi/agents/knutresource.desktop
        - /usr/share/kf5/akonadi_knut_resource/knut-template.xml
        - /usr/share/locale/*/LC_MESSAGES/akonadi_knut_resource.mo
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
