name       : akonadi
version    : 17.12.2
release    : 8
source     :
    - https://cdn.download.kde.org/stable/applications/17.12.2/src/akonadi-17.12.2.tar.xz : 6e4af5dc3a2cf4a7e6fa7b5e929c8aa467d6fdf1eb6799671a8c7b5ca82c9f0d
license    : LGPL-2.1
component  : desktop.library
summary    : The Akonadi framework is responsible for providing applications with a centralized database to store, index and retrieve the user's personal information.
description: |
    The Akonadi framework is responsible for providing applications with a centralized database to store, index and retrieve the user's personal information. This includes the user's emails, contacts, calendars, events, journals, alarms, notes, etc.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(libxslt)
    - pkgconfig(libpq)
    - pkgconfig(mariadb)
    - pkgconfig(Qt5Designer)
    - pkgconfig(sqlite3)
    - extra-cmake-modules
    - kcrash-devel
    - kdbusaddons-devel
    - kdesignerplugin-devel
    - ki18n-devel
    - kiconthemes-devel
    - kio-devel
    - kitemmodels-devel
    - kwindowsystem-devel
    - libboost-devel
    - shared-mime-info
rundeps    :
    - mariadb-server
patterns   :
    - devel : /usr/bin/akonadi_knut_resource
setup      : |
    %cmake .
build      : |
    %make
install    : |
    %make_install
