name       : akonadi
version    : 17.08.1
release    : 3
source     :
    - https://download.kde.org/stable/applications/17.08.1/src/akonadi-17.08.1.tar.xz : dcdc0b6069df48f3cc8e0a9e008e042c7173b2ed340103b7820bc517ef8312da
license    : LGPL-2.1
component  : desktop.library
summary    : The Akonadi framework is responsible for providing applications with
    a centralized database to store, index and retrieve the user's personal information.
description: |
    The Akonadi framework is responsible for providing applications with a centralized database to store, index and retrieve the user's personal information. This includes the user's emails, contacts, calendars, events, journals, alarms, notes, etc.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(libxslt)
    - pkgconfig(libpq)
    - pkgconfig(mariadb)
    - pkgconfig(Qt5Designer)
    - pkgconfig(sqlite3)
    - extra-cmake-modules
    - kcrash-devel
    - kdbusaddons-devel
    - kdesignerplugin-devel
    - ki18n-devel
    - kiconthemes-devel
    - kio-devel
    - kitemmodels-devel
    - kwindowsystem-devel
    - libboost-devel
    - shared-mime-info
patterns   :
    - devel : /usr/bin/akonadi_knut_resource
setup      : |
    %cmake .
build      : |
    %make
install    : |
    %make_install
