name       : akonadi
version    : 17.12.3
release    : 9
source     :
    - https://cdn.download.kde.org/stable/applications/17.12.3/src/akonadi-17.12.3.tar.xz : d135c40fd085eba1ee8b796c6017a81334221541e980065a28adcf31515acc00
license    : LGPL-2.1
component  : desktop.library
summary    : The Akonadi framework is responsible for providing applications with a centralized database to store, index and retrieve the user's personal information.
description: |
    The Akonadi framework is responsible for providing applications with a centralized database to store, index and retrieve the user's personal information. This includes the user's emails, contacts, calendars, events, journals, alarms, notes, etc.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(libxslt)
    - pkgconfig(libpq)
    - pkgconfig(mariadb)
    - pkgconfig(Qt5Designer)
    - pkgconfig(sqlite3)
    - extra-cmake-modules
    - kcrash-devel
    - kdbusaddons-devel
    - kdesignerplugin-devel
    - ki18n-devel
    - kiconthemes-devel
    - kio-devel
    - kitemmodels-devel
    - kwindowsystem-devel
    - libboost-devel
    - shared-mime-info
rundeps    :
    - mariadb-server
patterns   :
    - devel : /usr/bin/akonadi_knut_resource
setup      : |
    %cmake .
build      : |
    %make
install    : |
    %make_install
