name       : akonadi
version    : 18.04.0
release    : 10
source     :
    - https://cdn.download.kde.org/stable/applications/18.04.0/src/akonadi-18.04.0.tar.xz : 8d2023a7b0ec414dbb2199a7e84f5a085d934f9487048509af78082ea6618be9
license    : LGPL-2.1
component  : desktop.library
optimize   : lto
summary    : The Akonadi framework is responsible for providing applications with a centralized database to store, index and retrieve the user's personal information.
description: |
    The Akonadi framework is responsible for providing applications with a centralized database to store, index and retrieve the user's personal information. This includes the user's emails, contacts, calendars, events, journals, alarms, notes, etc.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(libxslt)
    - pkgconfig(libpq)
    - pkgconfig(mariadb)
    - pkgconfig(Qt5Designer)
    - pkgconfig(sqlite3)
    - extra-cmake-modules
    - kcrash-devel
    - kdbusaddons-devel
    - kdesignerplugin-devel
    - ki18n-devel
    - kiconthemes-devel
    - kio-devel
    - kitemmodels-devel
    - kwindowsystem-devel
    - libboost-devel
    - shared-mime-info
rundeps    :
    - mariadb-server
patterns   :
    - devel : /usr/bin/akonadi_knut_resource
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
